import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Open_Sans, Cormorant_Garamond } from "next/font/google";

export const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const comrmorantGaramond = Cormorant_Garamond({
  variable: "--font-cormorant-garamond", 
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn("antialiased bg-background text-foreground",comrmorantGaramond.className, openSans.className)}  
      >
        {children}
      </body>
    </html>
  );
}
